version: "3.9"
services:
  vpn:
    build: .
    cap_add:
      - NET_ADMIN # Required
      - NET_RAW # Required
    container_name: nordvpn
    environment:
      - USER=$NORD_USERNAME
      - PASS=$NORD_PASSWORD
      - CONNECT=France
      - TECHNOLOGY=NordLynx
      - DB_FILE=crossriver.db
      - EMAIL=a@b.com
      - STATE="CROSS RIVER"
    volumes:
      - .:/src
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only
